<?php
/**
 * DeliveryspecPreferences
 *
 * PHP version 5
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Canada Post REST Client
 *
 * Library for Canada Post REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CanadaPost\Model;

use \ArrayAccess;
use \CanadaPost\ObjectSerializer;

/**
 * DeliveryspecPreferences Class Doc Comment
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeliveryspecPreferences implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'deliveryspec_preferences';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'show_packing_instructions' => 'bool',
        'show_postage_rate' => 'bool',
        'show_insured_value' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'show_packing_instructions' => null,
        'show_postage_rate' => null,
        'show_insured_value' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'show_packing_instructions' => 'show-packing-instructions',
        'show_postage_rate' => 'show-postage-rate',
        'show_insured_value' => 'show-insured-value'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'show_packing_instructions' => 'setShowPackingInstructions',
        'show_postage_rate' => 'setShowPostageRate',
        'show_insured_value' => 'setShowInsuredValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'show_packing_instructions' => 'getShowPackingInstructions',
        'show_postage_rate' => 'getShowPostageRate',
        'show_insured_value' => 'getShowInsuredValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['show_packing_instructions'] = isset($data['show_packing_instructions']) ? $data['show_packing_instructions'] : null;
        $this->container['show_postage_rate'] = isset($data['show_postage_rate']) ? $data['show_postage_rate'] : null;
        $this->container['show_insured_value'] = isset($data['show_insured_value']) ? $data['show_insured_value'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets show_packing_instructions
     *
     * @return bool
     */
    public function getShowPackingInstructions()
    {
        return $this->container['show_packing_instructions'];
    }

    /**
     * Sets show_packing_instructions
     *
     * @param bool $show_packing_instructions show_packing_instructions
     *
     * @return $this
     */
    public function setShowPackingInstructions($show_packing_instructions)
    {
        $this->container['show_packing_instructions'] = $show_packing_instructions;

        return $this;
    }

    /**
     * Gets show_postage_rate
     *
     * @return bool
     */
    public function getShowPostageRate()
    {
        return $this->container['show_postage_rate'];
    }

    /**
     * Sets show_postage_rate
     *
     * @param bool $show_postage_rate mandatory for international shipping
     *
     * @return $this
     */
    public function setShowPostageRate($show_postage_rate)
    {
        $this->container['show_postage_rate'] = $show_postage_rate;

        return $this;
    }

    /**
     * Gets show_insured_value
     *
     * @return bool
     */
    public function getShowInsuredValue()
    {
        return $this->container['show_insured_value'];
    }

    /**
     * Sets show_insured_value
     *
     * @param bool $show_insured_value mandatory for international insured shipping
     *
     * @return $this
     */
    public function setShowInsuredValue($show_insured_value)
    {
        $this->container['show_insured_value'] = $show_insured_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


