<?php
/**
 * DeliveryOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Canada Post REST Client
 *
 * Library for Canada Post REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CanadaPost\Model;

use \ArrayAccess;
use \CanadaPost\ObjectSerializer;

/**
 * DeliveryOption Class Doc Comment
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeliveryOption implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'delivery-option';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'option_code' => 'string',
        'option_amount' => 'float',
        'option_qualifier_1' => 'boolean',
        'option_qualifier_2' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
		'option_code' => null,
		'option_amount' => null,
		'option_qualifier_1' => null,
		'option_qualifier_2' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
		'option_code' => 'option-code',
		'option_amount' => 'option-amount',
		'option_qualifier_1' => 'option-qualifier-1',
		'option_qualifier_2' => 'option-qualifier-2'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
		'option_code' => 'setOptionCode',
		'option_amount' => 'setOptionAmount',
		'option_qualifier_1' => 'setOptionQualifier1',
		'option_qualifier_2' => 'setOptionQualifier2'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
		'option_code' => 'getOptionCode',
		'option_amount' => 'getOptionAmount',
		'option_qualifier_1' => 'getOptionQualifier1',
		'option_qualifier_2' => 'getOptionQualifier2'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['option_code'] = isset($data['option_code']) ? $data['option_code'] : null;
        $this->container['option_amount'] = isset($data['option_amount']) ? $data['option_amount'] : null;
        $this->container['option_qualifier_1'] = isset($data['option_qualifier_1']) ? $data['option_qualifier_1'] : null;
        $this->container['option_qualifier_2'] = isset($data['option_qualifier_2']) ? $data['option_qualifier_2'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets option_code
     *
     * @return string
     */
    public function getOptionCode()
    {
        return $this->container['option_code'];
    }

    /**
     * Sets option_code
     *
     * @param string $option_code option_code
     *
     * @return $this
     */
    public function setOptionCode($option_code)
    {
        $this->container['option_code'] = $option_code;

        return $this;
    }

    /**
     * Gets option_amount
     *
     * @return float
     */
    public function getOptionAmount()
    {
        return $this->container['option_amount'];
    }

    /**
     * Sets option_amount
     *
     * @param float $option_amount option_amount
     *
     * @return $this
     */
    public function setOptionAmount($option_amount)
    {
        $this->container['option_amount'] = $option_amount;

        return $this;
    }

    /**
     * Gets option_qualifier_1
     *
     * @return bool
     */
    public function getOptionQualifier1()
    {
        return $this->container['option_qualifier_1'];
    }

    /**
     * Sets option_qualifier_1
     *
     * @param bool $option_qualifier_1 option_qualifier_1
     *
     * @return $this
     */
    public function setOptionQualifier1($option_qualifier_1)
    {
        $this->container['option_qualifier_1'] = $option_qualifier_1;

        return $this;
    }

	/**
	 * Gets option_qualifier_2
	 *
	 * @return bool
	 */
	public function getOptionQualifier2()
	{
		return $this->container['option_qualifier_2'];
	}

	/**
	* Sets option_qualifier_2
	*
	* @param bool $option_qualifier_2 option_qualifier_2
	*
	* @return $this
	*/
	public function setOptionQualifier2($option_qualifier_2)
	{
		$this->container['option_qualifier_2'] = $option_qualifier_2;

		return $this;
	}

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


