<?php
/**
 * DeliveryspecPreferencesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Canada Post REST Client
 *
 * Library for Canada Post REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CanadaPost;

/**
 * DeliveryspecPreferencesTest Class Doc Comment
 *
 * @category    Class
 * @description DeliveryspecPreferences
 * @package     CanadaPost
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeliveryspecPreferencesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeliveryspecPreferences"
     */
    public function testDeliveryspecPreferences()
    {
    }

    /**
     * Test attribute "show_packing_instructions"
     */
    public function testPropertyShowPackingInstructions()
    {
    }

    /**
     * Test attribute "show_postage_rate"
     */
    public function testPropertyShowPostageRate()
    {
    }

    /**
     * Test attribute "show_insured_value"
     */
    public function testPropertyShowInsuredValue()
    {
    }
}
