<?php
/**
 * DeliverySpecTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Canada Post REST Client
 *
 * Library for Canada Post REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CanadaPost;

/**
 * DeliverySpecTest Class Doc Comment
 *
 * @category    Class
 * @description DeliverySpec
 * @package     CanadaPost
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeliverySpecTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeliverySpec"
     */
    public function testDeliverySpec()
    {
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "parcel_characteristics"
     */
    public function testPropertyParcelCharacteristics()
    {
    }

    /**
     * Test attribute "print_preferences"
     */
    public function testPropertyPrintPreferences()
    {
    }

    /**
     * Test attribute "preferences"
     */
    public function testPropertyPreferences()
    {
    }

    /**
     * Test attribute "references"
     */
    public function testPropertyReferences()
    {
    }

    /**
     * Test attribute "customs"
     */
    public function testPropertyCustoms()
    {
    }

    /**
     * Test attribute "settlement_info"
     */
    public function testPropertySettlementInfo()
    {
    }
}
