<?php
/**
 * DeliveryItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Canada Post REST Client
 *
 * Library for Canada Post REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CanadaPost;

/**
 * DeliveryItemTest Class Doc Comment
 *
 * @category    Class
 * @description DeliveryItem
 * @package     CanadaPost
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeliveryItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeliveryItem"
     */
    public function testDeliveryItem()
    {
    }

    /**
     * Test attribute "customs_number_of_units"
     */
    public function testPropertyCustomsNumberOfUnits()
    {
    }

    /**
     * Test attribute "customs_unit_of_measure"
     */
    public function testPropertyCustomsUnitOfMeasure()
    {
    }

    /**
     * Test attribute "customs_description"
     */
    public function testPropertyCustomsDescription()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "hs_tariff_code"
     */
    public function testPropertyHsTariffCode()
    {
    }

    /**
     * Test attribute "unit_weight"
     */
    public function testPropertyUnitWeight()
    {
    }

    /**
     * Test attribute "customs_value_per_unit"
     */
    public function testPropertyCustomsValuePerUnit()
    {
    }

    /**
     * Test attribute "country_of_origin"
     */
    public function testPropertyCountryOfOrigin()
    {
    }
}
