<?php
/**
 * TransmitSetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CanadaPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Canada Post REST Client
 *
 * Library for Canada Post REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CanadaPost;

/**
 * TransmitSetTest Class Doc Comment
 *
 * @category    Class
 * @description TransmitSet
 * @package     CanadaPost
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransmitSetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransmitSet"
     */
    public function testTransmitSet()
    {
    }

    /**
     * Test attribute "group_ids"
     */
    public function testPropertyGroupIds()
    {
    }

    /**
     * Test attribute "requested_shipping_point"
     */
    public function testPropertyRequestedShippingPoint()
    {
    }

    /**
     * Test attribute "cpc_pickup_indicator"
     */
    public function testPropertyCpcPickupIndicator()
    {
    }

    /**
     * Test attribute "method_of_payment"
     */
    public function testPropertyMethodOfPayment()
    {
    }

    /**
     * Test attribute "manifest_address"
     */
    public function testPropertyManifestAddress()
    {
    }
}
